id: AEE85A9D4
title: A Prayer to Orgyen Dorje Chang
type: translation
pechas:
- I65926050
- IBE58ED9B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:11:03.125110
  last_modified_at: 2023-01-04 12:11:03.125114
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I65926050/C5C2: D8C9
  IBE58ED9B/D72D: D8C9
